### ISSUE TITLE
For FS22... no work

### ISSUE THREAD

**Issue by Vanquish081** [Donkie/I3DShapesTool#18]
Does not work with FS22 files

**Comment by kbrandwijk** [comment]
I won't say too much, but read the error message carefully, and it should be clear how to fix the error.

**Comment by Vanquish081** [comment]
That no work with FS22 shapes files

**Comment by Donkie** [comment]
Yeah something has probably changed in FS22. I will look into it whenever I have time.

**Comment by Possemaster** [comment]
Yes, Please update if you have the time. I'd love to have to have it compatible with FS22. Used it a lot in FS19.
I really need to export the sky.i3d.shapes file as I need to MOD in a new Sun and Moon as the Sun and moon in FS22 are hideous :)

**Comment by kbrandwijk** [comment]
Just for exporting to obj, it works. I would have submitted a PR to just update supported version range to <=7 instead of <=5, but I don't have time to do end to end testing. In the meantime, if you manually change the version in the shapes files to 5, the exporter will just work (the seed it finds is correct for regular and protected shapes files). Just make sure you change the version back to 7 or GE will crash on it.

**Comment by Donkie** [comment]
I tried simply letting it export for version 7 as you said @kbrandwijk but the output model is garbage so something must've changed (tried the bigMasterWesternWCF.i3d model). I will look into it more soon.

**Comment by Donkie** [comment]
Latest release should support all files up to and including FS22 now. Please make a new ticket if something doesn't work.
